### ISSUE TITLE
Database Schema II

### ISSUE THREAD

**Issue by ssoonmi** [luqven/iTube#3]
`plays` 
- [ ] You probably don't want to have it so that a `user` viewing a single `video` as unique. A `user` can view/`play` a `video` multiple times
---
`channels`
- You can add maybe a `description` or other things later when you create the functionality for it.
---
`subscriptions`
- [ ] If you want to implement `subscriptions`, you should have a separate `subscriptions` table. Since one `user` can be subscribed to many `channels`, and one `channel` can have many `subscribers`, you can't have a foreign key on the `channels` or the `users` that relates the two. You need a separate `subscriptions` table.
---
`videos`
- [ ] `user_id` shouldn't be necessary on the `videos` table because you can get the `user` through `channels`
---
`likes`
- [ ] Youtube has `likes` and dis`likes`. You may want a column on your `likes` table that will distinguish between the two
- [ ] `user_id` shouldn't be unique because a `user` can `like` many `videos`. 
---
`comments`
- [ ] `user_id` shouldn't be unique because a `user` can `like` many `comments`. (and possibly `channels`)
---

If you don't think some of these suggestions are appropriate, please comment below!

_Originally posted by @ssoonmi in https://github.com/luqven/Fullstack_Project/issues/2#issuecomment-455243270_

**Comment by luqven** [comment]
Made the suggested changes. Hopefully, it's looking a little better.  

I can see now that I'm going to have to get comfortable with the fact I'll have quite a few tables to manage, simply no way around that.
