### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by ssoonmi** [luqven/iTube#4]
`users`
- [ ] I don't think you need to keep track of what `videos` a `user` has uploaded since `channels` have a record of what `videos` they have.
---
`plays`
- [ ] instead of having a separate slice of state for `plays`, I think it's better to keep track of the `played` `videos` as `video` `ids` on the `user`. 
---
`likes`
- [ ] instead of having a separate slice of state for `likes`, I think it's better to keep track of the `liked` `videos` as `video` `ids` on the `user`.
---
`comments`
- [ ] probably want to have the `body` of a `comment` on the `comments` themselves.
---
`channels`
- [ ] I don't think you need a `channel` to have all the `subscribed users`. Probably just need the number of `subscriptions` stored there
---
`errors`
- [ ] delete `chirpForm` key lol
---

Nice job!
As always, if you don't think some of these suggestions are appropriate, please comment below!

**Comment by luqven** [comment]
Thanks for the feedback! Implemented the above, hopefully, it's looking better. Definitely more manageable than before. Had a hard time separating the needs of the state vs that of the back end tables at first.
